apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/env: production
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: test
      app.kubernetes.io/env: production
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
        app.kubernetes.io/env: production
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
