apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
  namespace: default
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/env: development
    app.kubernetes.io/project: test
spec:
  replicas: 5
  selector:
    matchLabels:
      apps.kubernetes.io/name: test
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
